export const GET_USER_INFO = "GET_USER_INFO";
export const GET_FEATURES_VALUE = "GET_FEATURES_VALUE";
export const GET_NEWRELEASES_VALUE = "GET_NEWRELEASES_VALUE";

// export const TOGGLE_CREATE_MODAL = "TOGGLE_CREATE_MODAL";
// export const TOGGLE_DELETE_MODAL = "TOGGLE_DELETE_MODAL";
export const TOGGLE_MODAL = 'TOGGLE_MODAL'

export const ADD_PLAYLIST = "ADD_PLAYLIST";
export const DELETE_PALYLIST = "DELETE_PLAYLIST";
export const LOAD_PLAYLISTS = 'LOAD_PLAYLISTS'
export const UPDATE_SINGLE_PLAYLIST = 'LOAD_SINGLE_PLAYLIST'
// export const ADD_TRACK_TO_PLAYLIST = 'ADD_TRACK_TO_PLAYLIST'